pipeline:
  build:
    image: node:lts
    commands:
      - npm install
      - npm run build
  deploy-dev:
    image: alpine
    secrets:
      - FTP_HOST
      - FTP_USERNAME
      - FTP_PASSWORD
    commands:
      - which lftp || ( apk --update add lftp )
      - lftp -e "set ftp:ssl-force true; set ssl:verify-certificate no; mirror -R ./dist/ dev.sp-magic.de/; bye" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
    when:
      branch:
        - develop
      event:
        - push
  deploy:
    image: alpine
    secrets:
      - FTP_HOST
      - FTP_USERNAME
      - FTP_PASSWORD
    commands:
      - which lftp || ( apk --update add lftp )
      - lftp -e "set ftp:ssl-force true; set ssl:verify-certificate no; mirror -R ./dist/ sp-magic.de/; bye" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
    when:
      branch:
        - main
      event:
        - push
